#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.pateltarang.com" # the base hostname & protocol for your site, e.g. http://example.com

# This description will show up in google search results
# (for index page) etc.
description: >
    mobile, mobile apps, iphone, ipad, iOS, swift, objective-C, application, apps, software development, software architecture, design patterns, software, technology, tarang, patel, tarang patel, patel tarang, pateltarang, tarangpatel, tarangp, montreal, canada
    
# This will what will show against &copy; in the footer
copyright: TarangPatel

short_bio: >
    iOS Developer fluent in Swift
    
favicon: true
favicon_location: "images/favicon.ico"
#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/blog/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:slug

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
