# User Settings | Edit there as per required

title: TarangPatel
url: "www.pateltarang.com"
#baseurl: "http://tarangpatel.github.io/tarangp/"

# This will show up at the top of index page
site_heading: >
    <font color="red">Tarang Patel</font>

email: tarangpatel2@yahoo.co.in
author: tarang patel
# This description will show up in google search results
# (for index page) etc.
description: >
    mobile, mobile apps, iphone, ipad, iOS, swift, objective-C, application, apps, software development, software architecture, design patterns, software, technology, tarang, patel, tarang patel, patel tarang, pateltarang, tarangpatel, tarangp, montreal, canada

# This will what will show against &copy; in the footer
copyright: TarangPatel
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: true         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Software engineer with experties in Mobile Apps Develpoment, Software Design and Architecture, Full-stack mobile solutions. I provide services like consulting on digital transformation, bootstrap mobile first solution, code-review, mentoring and more. Please contact for details. 

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Engineer, Photographer and Dreamer

about_footer: true

github_username: tarangpatel
linkedin_id: tarangspatel
instagram_id: tarang5
email_md5: ad7e59f9114404533469f87b323bec5d

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: "images/logo.png"
paginate: 7
paginate_path: "/page/:num"
tracking_id: UA-42678071-2  #UA-69243698-7 # GA Tracking IsD

# Social Stuff | open graph and twitter cards
og_image: "images/logo.png" # This will show in facebook thumbnails

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate
    - jekyll-redirect-from
    - jemoji

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
