#-------------------------------
# Site Settings
title: Tarang
author: Tarang Patel
description: A personal website of a software developer


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hello, I am Tarang.
  hero__description: I'm a software engineer and hobbyist photographer. I invite you to navigate my portfolio to know a bit more about me and my work.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /images/bell.png
      title: MyBell
      description: Manage you Bell account <a href="https://apps.apple.com/ca/app/mybell/id850549838">AppStore</a>
    
    - image: /images/virgin.png
      title: Virgin Plus My Account
      description: Virgin app for virgin account <a href="https://apps.apple.com/ca/app/virgin-plus-my-account/id853116586">AppStore</a>
    
    - image: /images/lucky.png
      title: Lucky Mobile My Account
      description: Mobile app for Lucky mobile <a href="https://apps.apple.com/ca/app/lucky-mobile-my-account/id1459173378">AppStore</a>
    
    - image: /images/cityparking.png
      title: City Parking
      description: A parking app <a href="https://apps.apple.com/ca/app/cityparking-parking-app/id1084431369">AppStore</a>

    - image: /images/level.png
      title: VSP Level
      description: Step counter app <a href="https://apps.apple.com/us/app/level-smart-glasses/id1336625786">AppStore</a>

    - image: /images/quickseries.png
      title: QuickSeries
      description: A bunch of publication app <a href="https://apps.apple.com/us/app/quickseries/id1424521895">AppStore</a>

    - image: /images/trow.png
      title: T. Rowe Price Personal
      description: Investment App <a href="https://apps.apple.com/us/app/t-rowe-price-personal/id534586266">AppStore</a>

#-------------------------------
# Subscribe Settings
#mailchimp:
 # mailchimp__title: Get updates and digital art inspiration # Add your Title
  #mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  #mailchimp__button__text: Subscribe # Add your button text.
  #mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-github", color: "#24292e", label: Github, link: "https://github.com/tarangpatel"}
- {icon: "ion-logo-linkedin", color: "#55acee", label: LinkedIn, link: "https://www.linkedin.com/in/tarangspatel"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com/tarang5"}

# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: tarangpatelinc@gmail.com # Add your email for contact form
  description:

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

#disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: UA-42678071-2
